### ISSUE TITLE
Wrong key size

### ISSUE THREAD

**Issue by IgorGanapolsky** [hummatli/SimpleEncryptionLib#3]
Hello,
I am unable to use your library to decrypt strings.  I get an error:
> Wrong key size
        at javax.crypto.spec.DESKeySpec.<init>(DESKeySpec.java:155)
        at com.mobapphome.mahencryptorlib.MAHEncryptor.<init>(MAHEncryptor.java:29)
        at com.mobapphome.mahencryptorlib.MAHEncryptor.newInstance(MAHEncryptor.java:46)

**Comment by tntkhang** [comment]
Me either, how can resolve the "Wrong key size"?
